-- AlterTable
ALTER TABLE `OperatorLogEntry` ADD COLUMN `approvedBy` VARCHAR(191) NULL,
    ADD COLUMN `format` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `kind` ENUM('ACTION', 'DECISION') NOT NULL DEFAULT 'ACTION';

