-- Demo data for astral.
--
-- The administrator account is NOT created here any more. It used to be an
-- INSERT of a bcrypt hash of 'admin123', with the plaintext in a comment beside
-- it and the same credential published in the README -- identical on every
-- deployment that ever ran this file, on hosts that hold client findings.
--
-- Accounts now come from `npm run seed` in services/astral, which creates only
-- what the configuration asks for and prints a generated password once. See
-- README.md, "Creating the first account".
